### ISSUE TITLE
Мне не удалось собрать back-end

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/practice-2020-neurocats#9]
Сначала сборка вылетала из-за отсутствия Cython’а. Я установил Cython. Сборка начала вылетать из-за того, что для `blis` нужен процессор с поддержкой AVX-512 (регистры ZMM), а мой процессор (Intel® Core™ i5-2430M) их не поддерживает:
```
C:\Users\Mazdaywik\AppData\Local\Temp\pip-install-whpvfulq\blis\blis\_src\kernels\skx\3\bli_dgemm_skx_asm_16x12_l2.c:542:28: error: unknown register name 'zmm0' in asm

            "r13", "r14", "r15", "zmm0", "zmm1", "zmm2", "zmm3", "zmm4", "zmm5",
                                 ^
      .\frame\include\bli_x86_asm_macros.h:102:22: note: expanded from macro 'END_ASM'
      #define END_ASM(...) __VA_ARGS__ );
                           ^
      1 error generated.
```
`blis` нужен для `spacy`, а `spacy` нужен для чего-то ещё в `requirements.txt`.

Завтра попробую на другом компьютере.

**Comment by yukhrobak** [comment]
К сожалению, мы не заметили и в проекте было множество ошибок из-за одной из зависимостей нейронной сети (при запуске на linux и некоторых версиях windows).
Решение проблемы пока не найдено.
В данный момент мы удалили нейросеть из проекта, чтобы можно было оценить остальные части проекта.
